#/*******************************************************************************
# * \copyright   This file is part of the GADGET4 N-body/SPH code developed
# * \copyright   by Volker Springel. Copyright (C) 2014, 2015 by Volker Springel
# * \copyright   (volker.springel@h-its.org) and all contributing authors.
# *******************************************************************************/

RESULT     := $(shell mkdir -p $(BUILD_DIR)  )

all: $(BUILD_DIR)/gadgetconfig.h 

$(BUILD_DIR)/gadgetconfig.h:  $(CONFIG) buildsystem/config.py
	$(PYTHON) buildsystem/config.py $(CONFIG) $(BUILD_DIR) $(CURDIR) $(SRC_DIR)
