theme: jekyll-theme-slate
domain: https://weiguangcui.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://weiguangcui.github.io/Gadget4/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /Gadget4/docs      # place folder name if the site is served in a subfolder   
